In [1]:
import chardet
import math
import numpy as np
import csv
import pandas as pd
import random

from sqlalchemy import create_engine

## Getting slices

In [2]:
#slice0 = pd.read_csv('data/slice-0.tsv', sep='\t', index_col='id')
slice0 = pd.read_csv('data/slice-0.tsv.gzip', sep='\t', compression="gzip", index_col='id')
slice0 = slice0.rename(str.lower, axis='columns')

In [3]:
slice1 = pd.read_csv('data/slice-1.csv', index_col='id')
slice1 = slice1.rename(str.lower, axis='columns')

In [4]:
slice2 = pd.read_json('data/slice-2.json')
slice2 = slice2.set_index("id")
slice2 = slice2.rename(str.lower, axis='columns')

In [5]:
slice3 = pd.read_json('data/slice-3.json', lines=True)
slice3 = slice3.set_index('id')
slice3 = slice3.rename(str.lower, axis='columns')

In [6]:
slice4 = pd.read_csv('data/slice-4.csv', index_col='id')
slice4 = slice4.rename(str.lower, axis='columns')

In [7]:
slice5 = pd.read_csv('data/slice-5.txt', index_col='id')
slice5 = slice5.rename(str.lower, axis='columns')

In [8]:
slice6 = pd.read_json('data/slice-6.json')
slice6 = slice6.set_index('id')

slice6 = slice6.rename(str.lower, axis='columns')

In [9]:
slice_scrapping = pd.read_csv('webscraping.csv', index_col='id')
slice_scrapping = slice_scrapping.rename(str.lower, axis='columns')

In [10]:
# Db settings - PostgreSQL
username = 'ldsa_student'
password = 'R4Fr4P3aAgMYBqqP'  # the password is not XXX by the way
host_name = 'batch4-s02-db-instance.ctq2kxc7kx1i.eu-west-1.rds.amazonaws.com'
port = 5432
db_name = 'batch4_s02_db'
schema = 'hackathon_students'

conn_str = 'postgresql://{}:{}@{}:{}/{}'.format(username, password, host_name, port, db_name)
conn_args = {'options': '-csearch_path={}'.format(schema)}

engine = create_engine(conn_str, connect_args=conn_args)

query = 'SELECT * FROM missingdata'

slice_database = pd.read_sql_query(query, engine)
slice_database = slice_database.set_index('id')
slice_database = slice_database.rename(str.lower, axis='columns')

In [11]:
slices = [slice0, slice1, slice2, slice3, slice4, slice5, slice6, slice_scrapping, slice_database]

## Display slice info

In [12]:
# Shape
for s in slices:
    print(s.shape)

(1432, 13)
(2145, 32)
(2027, 31)
(2187, 14)
(1744, 32)
(1201, 11)
(1201, 10)
(2665, 38)
(2666, 39)

In [13]:
test_columns = ['id', 'NumDots', 'SubdomainLevel', 'PathLevel', 'UrlLength', 'NumDash', 'NumDashInHostname', 'AtSymbol', 'TildeSymbol', 'NumUnderscore', 'NumPercent', 'NumQueryComponents', 'NumAmpersand', 'NumHash', 'NumNumericChars', 'NoHttps', 'RandomString', 'IpAddress', 'DomainInSubdomains', 'DomainInPaths', 'HttpsInHostname', 'HostnameLength', 'PathLength', 'QueryLength', 'DoubleSlashInPath', 'NumSensitiveWords', 'EmbeddedBrandName', 'PctExtHyperlinks', 'PctExtResourceUrls', 'ExtFavicon', 'InsecureForms', 'RelativeFormAction', 'ExtFormAction', 'AbnormalFormAction', 'PctNullSelfRedirectHyperlinks', 'FrequentDomainNameMismatch', 'FakeLinkInStatusBar', 'RightClickDisabled', 'PopUpWindow', 'SubmitInfoToEmail', 'IframeOrFrame', 'MissingTitle', 'ImagesOnlyInForm', 'SubdomainLevelRT', 'UrlLengthRT', 'PctExtResourceUrlsRT', 'AbnormalExtFormActionR', 'ExtMetaScriptLinkRT', 'PctExtNullSelfRedirectHyperlinksRT']
test_columns = [c.lower() for c in test_columns]

## Merging

In [14]:
df = (pd
      .concat(slices, axis=0)
      .drop(['unnamed: 0', "index"], axis=1))

In [15]:
df.groupby(level=0).mean()

,domaininpaths,querylength,rightclickdisabled,domaininsubdomains,extfavicon,nohttps,hostnamelength,numunderscore,fakelinkinstatusbar,doubleslashinpath,...,numquerycomponents,insecureforms,urllength,pctnullselfredirecthyperlinks,numdots,frequentdomainnamemismatch,numsensitivewords,pathlength,extformaction,pctexthyperlinks
id,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,1.0,1.0,21.0,0.0,0.0,0.0,...,0.0,1.0,72.0,0.0,3.0,0.0,0.0,44.0,0.0,0.0
4,1.0,0.0,0.0,0.0,1.0,1.0,22.0,0.0,0.0,0.0,...,0.0,1.0,79.0,0.0,3.0,0.0,0.0,50.0,0.0,0.0
5,1.0,0.0,0.0,0.0,0.0,1.0,10.0,0.0,0.0,0.0,...,0.0,0.0,46.0,0.0,3.0,0.0,0.0,29.0,1.0,0.0
7,1.0,0.0,0.0,0.0,0.0,1.0,17.0,0.0,0.0,0.0,...,0.0,1.0,60.0,0.0,2.0,0.0,0.0,36.0,0.0,0.0
9,1.0,0.0,0.0,1.0,0.0,1.0,65.0,0.0,0.0,0.0,...,0.0,1.0,76.0,0.0,8.0,0.0,0.0,4.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9998,0.0,0.0,0.0,0.0,0.0,1.0,16.0,0.0,0.0,0.0,...,0.0,1.0,57.0,0.0,2.0,0.0,0.0,34.0,0.0,0.0
9999,0.0,13.0,0.0,0.0,0.0,1.0,15.0,0.0,0.0,0.0,...,1.0,1.0,49.0,0.0,3.0,0.0,0.0,13.0,0.0,0.0
dit is poep,0.0,0.0,0.0,0.0,0.0,1.0,16.0,0.0,0.0,0.0,...,0.0,1.0,54.0,0.0,1.0,0.0,0.0,31.0,0.0,0.0
ontlasting in plaats van een id,0.0,0.0,0.0,0.0,0.0,1.0,10.0,0.0,0.0,0.0,...,0.0,0.0,68.0,0.0,1.0,0.0,0.0,51.0,0.0,0.0
एक id . के बजाय हिंदी में मल,0.0,0.0,0.0,0.0,0.0,1.0,15.0,0.0,0.0,0.0,...,0.0,1.0,53.0,0.0,2.0,0.0,0.0,31.0,0.0,0.0

In [16]:
new_df = df.groupby(level=0).mean()

In [17]:
new_df = new_df.drop(new_df.index[-3:])

In [18]:
new_df.isnull().sum()

domaininpaths                     31
querylength                       29
rightclickdisabled               287
domaininsubdomains                99
extfavicon                        34
nohttps                          331
hostnamelength                     2
numunderscore                      0
fakelinkinstatusbar               16
doubleslashinpath                124
pctextresourceurls                32
atsymbol                           1
class_label                        0
numnumericchars                   66
relativeformaction                71
ipaddress                        195
tildesymbol                       36
numhash                            7
httpsinhostname                   68
subdomainlevel                     6
pathlevel                         25
randomstring                      35
numdashinhostname                521
numpercent                         8
abnormalformaction                 3
embeddedbrandname                 75
numdash                          218
numampersand                      66
numquerycomponents                30
insecureforms                      3
urllength                         68
pctnullselfredirecthyperlinks      5
numdots                          186
frequentdomainnamemismatch        34
numsensitivewords                263
pathlength                       267
extformaction                    167
pctexthyperlinks                 922
dtype: int64

In [19]:
new_df["id"] = new_df.index

In [20]:
new_df.id.astype("int64").reset_index(drop=True).to_csv("correct_ids.csv")

In [21]:
pd.read_csv("correct_ids.csv")

      Unnamed: 0    id
0              0     1
1              1     4
2              2     5
3              3     7
4              4     9
...          ...   ...
7989        7989  9982
7990        7990  9988
7991        7991  9991
7992        7992  9998
7993        7993  9999

[7994 rows x 2 columns]

In [22]:
new_df.index

Index([     1,      4,      5,      7,      9,     10,     11,     13,     14,
           18,
       ...
       '9967', '9975', '9976', '9978',  '998', '9982', '9988', '9991', '9998',
       '9999'],
      dtype='object', name='id', length=7994)

In [23]:
new_df.to_csv("all_data.csv")

In [24]:
new_df.class_label.unique()

array([1, 0])